name: Check plugin versions

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        env:
          API_TOKEN: ${{ secrets.TOKEN }}
        run: |
          ./check-version.sh
