name: Generate actions file

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.github/**'
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}


      - run: ./generate-actions.sh

      - name: Commit and push changes
        continue-on-error: true
        run: |
          git config --global user.name "File Update"
          git config --global user.email "mail@example.com"
          git add .
          git commit -m "github actions update"
          git push
